const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
// All values below are browser-test fixtures, never production data.
(async () => {
 const server = http.createServer((req,res)=>{let file=path.join(__dirname,new URL(req.url,'http://localhost').pathname);if(file.endsWith(path.sep))file+='index.html';fs.readFile(file,(e,data)=>{if(e)return res.writeHead(404).end();res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(data);});});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 try {
  const page=await browser.newPage({viewport:{width:1440,height:900}}), errors=[], requests=[];page.on('pageerror',e=>errors.push(e.message));
  let mode='populated', delay=0;
  const now=()=>new Date().toISOString();
  const state=(bias,confidence)=>({available:true,freshness:'fresh',bias,confidence,score:63,long_permission:'ALLOWED',short_permission:'BLOCKED',state_version:'test-v2',generated_at:now(),updated_at:now()});
  const marketFixture=()=>({available:true,freshness:'FRESH',timestamp:now(),refresh_interval_seconds:60,price:100,price_change_24h:2,volume:100000,turnover:20000000,funding_rate:.00012,previous_funding_rate:.0001,funding_change:.00002,funding_state:'POSITIVE',funding_interval_hours:8,funding_previous_at:now(),open_interest:1000,open_interest_value:100000,oi_change_15m:1,oi_change_1h:4.2,oi_change_4h:7.1,price_return_15m:.2,price_return_1h:1,price_return_4h:2,oi_observed_at:now(),price_oi_state:'PRICE_UP_OI_UP',volume_change_15m:18,relative_volume_15m:1.18,volume_state:'NORMAL',volatility:.12,volatility_state:'MODERATE',candles_observed_at:now(),spread_bps:2,liquidity_state:'HIGH',premium_pct:.02,derivatives_bias:'BULLISH',derivatives_confidence:.75,provenance:{source:'bybit <script>'},component_errors:[],collector_version:'market-state-v1',logic_version:'derivatives-state-v1'});
  const decisionFixture=()=>({id:1,available:true,freshness:'FRESH',shadow_mode:true,execution_connected:false,decision:'GO',direction:'LONG',selected_timeframe:'1h',selection_confidence:.72,selected_score:82,decision_time:now(),model_version:'decision-engine-v1',selector_version:'horizon-selector-v1',reason_summary:'Strongest setup <script>alert(1)</script>',veto_reason:null,evidence:{configuration:{decision_max_age_seconds:600}},timeframe_assessments:Object.fromEntries(['15m','1h','4h'].map((tf,i)=>[tf,{direction:'LONG',status:i===0?'WEAK':'VALID',score:[58,82,71][i],confidence:.72,technical_score:.8,news_score:null,derivatives_score:1,market_score:.8,regime_score:null,risk_penalty:3,cost_penalty:2,reason_summary:'Safe reason <img src=x>',evidence:{selection_reason:tf==='1h'?'SELECTED':'LOWER_SCORE',expected_move_pct:null,unavailable_components:['news','regime']}}]))});
  const sizingFixture=()=>({opportunity_id:1,available:true,freshness:'FRESH',shadow_mode:true,execution_connected:false,currency:'USDT',risk_decision:'REDUCE',direction:'LONG',timeframe:'1h',decision_time:now(),evidence_expires_at:new Date(Date.now()+120000).toISOString(),base_stake:1000,decision_confidence:.86,confidence_band:'HIGH',confidence_multiplier:1.25,volatility_multiplier:.8,liquidity_multiplier:1,portfolio_multiplier:.9,correlation_multiplier:.7,directional_multiplier:1,timeframe_multiplier:1,raw_proposed_stake:630,final_proposed_stake:630,leverage:2,proposed_notional:1260,edge_check:{expected_move_pct:1,estimated_roundtrip_cost_bps:14},proposed_portfolio:{gross_notional:7260},reasons:[{component:'volatility',multiplier:.8},'Fixture <script>alert(1)</script>'],portfolio:{total_equity:30000,open_position_count:3,gross_notional:6000,long_notional:5000,short_notional:1000,utilization_pct:20,concentration_state:'MODERATE',observed_at:now()},sizing_version:'position-sizing-v1',risk_version:'portfolio-risk-v1',correlation_version:'correlation-risk-v1'});
  const learningFixture=()=>({available:true,shadow_mode:true,execution_connected:false,minimum_samples:20,champion:'learning-v1-baseline',challenger:'learning-v1-fixture-shadow',challenger_status:'EVALUATING',evaluator_version:'outcome-evaluator-v1',learning_version:'learning-engine-v1',health:{stale:false,status:'available'},timeframes:Object.fromEntries(['15m','1h','4h'].map(tf=>[tf,{observations:84,asset_specific_learning:true,weights:[{feature:'technical <script>alert(1)</script>',observation_count:84,effective_shadow_multiplier:1.08,fallback:'ASSET'},{feature:'REGULATORY',observation_count:2,effective_shadow_multiplier:.95,fallback:'GLOBAL'}],calibration:[{count:30,sufficient:true,predicted_confidence:.78,observed_success_rate:.71}]}])),horizon_performance:{observations:84,best_horizon_hit_rate:.64,mean_regret_pct:.2}});
  const detail=symbol=>({api_version:'2.0.0-phase1',asset:{symbol,name:symbol==='BTC'?'Bitcoin':'Ethereum',exchange:'bybit',market_type:'linear_perpetual'},overall_state:{...state('BULLISH',.72),overall_bias:'BULLISH',overall_confidence:.72,intelligence_score:75},timeframes:{'15m':state('NEUTRAL',.48),'1h':state('BULLISH',.72),'4h':state('BEARISH',.81)},news_summary:{news_bias:'BULLISH',news_score:.25,news_confidence:.6,relevant_story_count:2,recent_event_count:1,high_impact_event_count:0,recent_weighted_impact:.2,last_intelligence_update:now(),freshness:'fresh',classifier_version:'asset-news-v1'},learning:learningFixture(),market:marketFixture(),decision:decisionFixture(),sizing:sizingFixture(),versions:[{version:'foundation-v1',status:'FOUNDATION',description:'Schema metadata only'}]});
  const universe=()=>({schema_version:1,status:'ok',entry_eligible:true,universe_version:'test-v1',generated_at:now(),valid_until:new Date(Date.now()+600000).toISOString(),assets:'BTC ETH SOL XRP LINK ONDO AAVE UNI HYPE INJ'.split(' ').map((symbol,i)=>({symbol,pair:symbol+'/USDT:USDT',rank:i+1,opportunity_score:80-i,reason:'Test-only evidence',data_confidence:.8,trend:'positive'}))});
  await page.route('https://stream.radiorrr.com/**',r=>r.abort());
  await page.route('https://api.rrr.trading/**',async r=>{
   const p=new URL(r.request().url()).pathname;requests.push(p);
   if(p==='/api/trading-universe')return r.fulfill({json:universe()});
   if(p==='/api/market-summary')return r.fulfill({json:{currency:'USD',source:'kraken',markets:[{symbol:'BTC',price:123,updated_at:mode==='stale'?'2000-01-01':now()}]}});
   const m=/\/api\/v2\/intelligence\/assets\/([A-Z0-9]+)(?:\/(news|events))?$/.exec(p);
   if(!m)return r.fulfill({status:503});
   if(delay)await new Promise(resolve=>setTimeout(resolve,delay));
   if(mode==='failure'||mode==='missing')return r.fulfill({status:mode==='missing'?404:503});
   if(mode==='partial'&&m[2]==='news')return r.fulfill({status:503});
   const d=detail(m[1]);
   if(m[2])return r.fulfill({json:{asset:d.asset,status:mode==='empty'?'unavailable':mode==='degraded'?'degraded':'ok',[m[2]]:['populated','degraded','unknown-time'].includes(mode)?m[2]==='news'?[{headline:'Test headline <script>',source:'Fixture source',published_at:now(),confidence:.6,relevance_score:.7,impact_score:.4,direction:'BULLISH',event_type:'ETF',freshness:'fresh',classifier_version:'asset-news-v1',source_url:'https://example.test/story'}]:[{event_type:'TEST',description:'Fixture event',event_time:mode==='unknown-time'?null:now(),source:'Fixture source',importance:.4,confidence:.6,freshness:'stale',classifier_version:'asset-news-v1',source_url:'javascript:alert(1)'}]:[]}});
   if(mode==='learning-empty'){for(const f of Object.values(d.learning.timeframes)){f.observations=2;f.asset_specific_learning=false;f.weights=[];f.calibration=[];}d.learning.challenger=null;d.learning.horizon_performance.observations=2;}
   if(mode==='learning-stale')d.learning.health.stale=true;
   if(mode==='learning-missing')delete d.learning;
   if(mode==='learning-live')d.learning.execution_connected=true;
   if(mode==='learning-malformed'){d.learning.timeframes['1h'].weights=[{feature:'Impossible',observation_count:100,effective_shadow_multiplier:4.5,fallback:'ASSET'}];d.learning.timeframes['1h'].calibration=[];}
   if(mode==='shadow-no-go'){d.decision.decision='NO_GO';d.decision.selected_timeframe=null;d.decision.selection_confidence=null;d.decision.selected_score=null;d.decision.direction='NEUTRAL';d.decision.reason_summary='HORIZON_MARGIN_TOO_SMALL';}
   if(mode==='shadow-blocked'){d.decision.decision='BLOCKED';d.decision.veto_reason='BLOCKED_EXISTING_POSITION';d.decision.selected_timeframe=null;}
   if(mode==='shadow-stale'){d.decision.available=false;d.decision.freshness='STALE';d.decision.saved_decision='GO';d.decision.decision='INSUFFICIENT_DATA';}
   if(mode==='shadow-expired')d.decision.decision_time='2000-01-01';
   if(mode==='shadow-missing')delete d.decision;
   if(mode==='shadow-future')d.decision.decision_time=new Date(Date.now()+60000).toISOString();
   if(mode==='sizing-block'){d.sizing.risk_decision='BLOCK';d.sizing.final_proposed_stake=0;d.sizing.proposed_notional=0;d.sizing.block_reason='BLOCK_EXISTING_ASSET_POSITION';}
   if(mode==='sizing-missing')delete d.sizing;
   if(mode==='sizing-stale'){d.sizing.available=false;d.sizing.freshness='STALE';d.sizing.saved_proposal={risk_decision:'ALLOW'};}
   if(mode==='sizing-expired')d.sizing.evidence_expires_at='2000-01-01';
   if(mode==='sizing-live')d.sizing.execution_connected=true;
   if(mode==='sizing-race')d.sizing.opportunity_id=999;
   if(mode==='sizing-invalid-block'){d.sizing.risk_decision='BLOCK';d.sizing.final_proposed_stake=10;}
   if(mode==='sizing-timer')d.sizing.evidence_expires_at=new Date(Date.now()+1500).toISOString();
   if(mode==='market-missing')delete d.market;
   if(mode==='market-partial'){d.market.funding_rate=null;d.market.open_interest=null;d.market.oi_change_1h=null;d.market.derivatives_bias='UNKNOWN';d.market.derivatives_confidence=null;d.market.component_errors=['oi_history_unavailable'];}
   if(mode==='market-stale'){d.market.timestamp='2000-01-01';d.market.freshness='STALE';d.market.available=false;}
   if(mode==='market-failure'){d.market.available=false;d.market.source_error='Market source unavailable';d.market.freshness='UNAVAILABLE';}
   if(mode==='empty'){delete d.learning;delete d.market;d.overall_state={available:false,overall_bias:'UNKNOWN',overall_confidence:null};d.timeframes={};d.news_summary={news_bias:'UNKNOWN',news_score:null,news_confidence:null,relevant_story_count:0,freshness:'empty',classifier_version:'asset-news-v1'};}
   if(mode==='partial')delete d.timeframes['4h'];
   if(mode==='stale'){d.overall_state.generated_at='2000-01-01';d.timeframes['15m'].generated_at='2000-01-01';}
   return r.fulfill({json:d});
  });
  const base=`http://127.0.0.1:${server.address().port}`;await page.goto(base);await page.waitForSelector('.universe-bubble');
  const modal=page.locator('#asset-intelligence-dialog'), btc=page.locator('.universe-bubble').first(), x=page.getByRole('button',{name:'Close asset intelligence'});
  await btc.focus();await btc.press('Enter');await page.waitForSelector('#ai-news .ai-record');
  assert.match(await modal.innerText(),/BTC — Bitcoin/);assert(requests.includes('/api/v2/intelligence/assets/BTC'));assert(requests.includes('/api/v2/intelligence/assets/BTC/news'));assert(requests.includes('/api/v2/intelligence/assets/BTC/events'));
  for(const [frame,bias,confidence]of [['15m','NEUTRAL','48%'],['1h','BULLISH','72%'],['4h','BEARISH','81%']]){const text=await page.locator(`[data-timeframe="${frame}"]`).innerText();assert(text.includes(bias)&&text.includes(confidence));assert.match(text,/Long permission\s+ALLOWED/);}
  assert.match(await page.locator('#ai-price').innerText(),/\$123/);assert.match(await page.locator('#ai-news').innerText(),/Test headline <script>/);assert.equal(await page.locator('#ai-news script').count(),0);assert.match(await page.locator('#ai-news-summary').innerText(),/News score.*|−1 to \+1/);assert.match(await page.locator('#ai-news-summary').innerText(),/asset-news-v1/);assert.equal(await page.locator('#ai-news a').count(),1);assert.equal(await page.locator('#ai-events a').count(),0);assert.match(await page.locator('#ai-events').innerText(),/stale/);
  const marketText=await page.locator('#ai-market').innerText();assert.match(marketText,/Market & derivatives/);assert.match(marketText,/\+0\.012%/);assert.match(marketText,/4\.2%.*7\.1%/);assert.match(marketText,/PRICE UP OI UP/);assert.match(marketText,/BULLISH/);assert.match(marketText,/75%/);assert.match(marketText,/bybit <script>/);assert.equal(await page.locator('#ai-market script').count(),0);
  const decisionText=await page.locator('#ai-decision').innerText();assert.match(decisionText,/SHADOW MODE · NOT CONTROLLING TRADES/);assert.match(decisionText,/SHADOW GO/);assert.match(decisionText,/Best horizon\s+1h Medium Term/);assert.match(decisionText,/SELECTED · SHADOW ONLY/);assert.match(decisionText,/72%/);assert.match(decisionText,/no validated forecast/);assert.match(decisionText,/<script>alert/);assert.equal(await page.locator('#ai-decision script, #ai-decision img').count(),0);assert.equal(await page.locator('[data-decision-timeframe]').count(),3);
  assert.equal(await page.evaluate(()=>document.body.style.overflow),'hidden');assert.equal(await x.evaluate(e=>e===document.activeElement),true);
  await page.keyboard.press('Tab');assert(await page.evaluate(()=>document.activeElement.closest('dialog')!==null));
  for(const width of [320,375,768,1440]){await page.setViewportSize({width,height:700});assert(await modal.evaluate(e=>e.scrollWidth<=e.clientWidth+1),'modal overflow '+width);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.equal(await page.locator('.ai-timeframes').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),width<=700?1:3);assert.equal(await page.locator('.ai-market-grid').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),width<=700?1:2);if([375,1440].includes(width)){fs.mkdirSync('.runtime',{recursive:true});await page.screenshot({path:`.runtime/phase2-${width}.png`});}}
  await x.click();await page.waitForFunction(()=>!document.querySelector('dialog').open);assert.equal(await btc.evaluate(e=>e===document.activeElement),true);assert.equal(await page.evaluate(()=>document.body.style.overflow),'');
  await btc.click();await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('dialog').open);
  await btc.click();await page.mouse.click(1,1);await page.waitForFunction(()=>!document.querySelector('dialog').open);
  for(let i=0;i<3;i++){await btc.click();await x.click();await page.waitForFunction(()=>!document.querySelector('dialog').open);}
  for(const m of ['market-partial','market-stale','market-failure','market-missing']){mode=m;await btc.click();await page.waitForSelector('#ai-market');const text=await page.locator('#ai-market').innerText();assert.match(text,/Unavailable|unavailable/);if(m==='market-partial'){assert.match(text,/Funding rate \(per interval\)\s+Unavailable/);assert.match(text,/Open interest \(base units\)\s+Unavailable/);assert.match(text,/Partial data/);}if(m==='market-stale'){assert.match(text,/STALE/);assert.match(text,/Derivatives bias\s+UNKNOWN/);assert.match(text,/Saved values/);}if(m==='market-failure')assert.match(text,/Source refresh failed/);if(m==='market-missing')assert.match(text,/no valid snapshot recorded/);await x.click();}
  for(const m of ['shadow-no-go','shadow-blocked','shadow-stale','shadow-expired','shadow-future','shadow-missing']){mode=m;await btc.click();await page.waitForSelector('#ai-decision');const text=await page.locator('#ai-decision').innerText();assert.match(text,/SHADOW MODE · NOT CONTROLLING TRADES/);assert(!text.includes('SHADOW GO'));assert.match(text,/Best horizon\s+None/);if(m==='shadow-blocked')assert.match(text,/BLOCKED EXISTING POSITION/);if(m==='shadow-no-go')assert.match(text,/HORIZON_MARGIN_TOO_SMALL/);if(m==='shadow-stale')assert.match(text,/Saved result: GO/);await x.click();}
  mode='populated';await btc.click();await page.waitForSelector('#ai-decision');for(const width of [375,1440]){await page.setViewportSize({width,height:900});await page.locator('#ai-decision').scrollIntoViewIfNeeded();await page.screenshot({path:`.runtime/phase5-decision-${width}.png`});}await x.click();
  mode='populated';await btc.click();await page.waitForSelector('#ai-market');for(const width of [375,1440]){await page.setViewportSize({width,height:900});await page.locator('#ai-market').scrollIntoViewIfNeeded();await page.screenshot({path:`.runtime/phase4-market-${width}.png`});}await x.click();
  for(const m of ['populated','sizing-block','sizing-missing','sizing-stale','sizing-expired','sizing-live','sizing-race','sizing-invalid-block','shadow-no-go','shadow-stale']){
   mode=m;await btc.click();await page.waitForSelector('#ai-sizing');const text=await page.locator('#ai-sizing').innerText();assert.match(text,/SHADOW ONLY · NOT CONTROLLING TRADES/);
   if(m==='populated'){assert.match(text,/630 USDT/);assert.match(text,/1,260 USDT/);assert.match(text,/2×/);assert.match(text,/position-sizing-v1/);assert.match(text,/<script>alert/);assert.equal(await page.locator('#ai-sizing script').count(),0);}
   else if(m==='sizing-block'){assert.match(text,/BLOCK EXISTING ASSET POSITION/);assert.match(text,/0 USDT/);}
   else {assert(!text.includes('630 USDT'));assert.match(text,/unavailable or stale|no valid trade opportunity/);}
   await x.click();
  }
  mode='sizing-timer';await btc.click();await page.waitForSelector('#ai-sizing');await page.waitForFunction(()=>document.querySelector('#ai-sizing').textContent.includes('unavailable or stale'));assert(!(await page.locator('#ai-sizing').innerText()).includes('630 USDT'));await x.click();
  mode='populated';await btc.click();await page.waitForSelector('#ai-sizing');for(const width of [320,375,768,1440]){await page.setViewportSize({width,height:900});await page.locator('#ai-sizing').scrollIntoViewIfNeeded();assert(await modal.evaluate(e=>e.scrollWidth<=e.clientWidth+1));if([375,1440].includes(width))await page.screenshot({path:`.runtime/phase6-sizing-${width}.png`});}await x.click();
  for(const m of ['populated','learning-empty','learning-stale','learning-missing','learning-live','learning-malformed']){
   mode=m;await btc.click();await page.waitForSelector('#ai-learning');const text=await page.locator('#ai-learning').innerText();assert.match(text,/SHADOW LEARNING.*NO AUTOMATIC PROMOTION/);
   if(m==='populated'){assert.match(text,/learning-v1-baseline/);assert.match(text,/84/);assert.match(text,/\+0.08 shadow multiplier/);assert.match(text,/global fallback/);assert.match(text,/78%.*71%/);assert.equal(await page.locator('#ai-learning script').count(),0);}
   if(m==='learning-empty')assert.match(text,/Not enough history/);
   if(m==='learning-stale')assert.match(text,/saved history only/);
   if(m==='learning-missing'||m==='learning-live'){assert.match(text,/Learning history will appear/);assert(!text.includes('+0.08'));}
   if(m==='learning-malformed')assert(!text.includes('Impossible'));
   for(const width of [320,375,768,1440]){await page.setViewportSize({width,height:900});await page.locator('#ai-learning').scrollIntoViewIfNeeded();assert(await modal.evaluate(e=>e.scrollWidth<=e.clientWidth+1));if(m==='populated'&&[375,1440].includes(width))await page.screenshot({path:`.runtime/phase7-learning-${width}.png`});}await x.click();
  }
  mode='empty';await btc.click();await page.waitForSelector('#ai-events');await page.waitForFunction(()=>document.querySelector('#ai-events').textContent.includes('No events'));assert.match(await modal.innerText(),/UNKNOWN/);assert.match(await modal.innerText(),/No asset-specific intelligence has been recorded yet/);assert.match(await modal.innerText(),/Learning history will appear/);assert.equal(await page.locator('.ai-bias[data-tone]').count(),0);await x.click();
  for(const testMode of ['degraded','unknown-time']){mode=testMode;await btc.click();await page.waitForSelector('#ai-news .ai-record');if(testMode==='degraded')assert.match(await page.locator('#ai-news').innerText(),/degraded.*source collection health/);else assert.match(await page.locator('#ai-events').innerText(),/Event time unknown; publication is separate/);await x.click();}
  mode='partial';await btc.click();await page.waitForFunction(()=>document.querySelector('#ai-news')?.textContent.includes('unavailable.'));assert.match(await page.locator('[data-timeframe="4h"]').innerText(),/UNAVAILABLE/);await x.click();
  mode='stale';await btc.click();await page.waitForFunction(()=>document.querySelector('#ai-price')?.textContent.includes('stale'));assert.match(await modal.innerText(),/STALE · saved assessment/);await x.click();
  for(const [m,text]of [['failure','Asset intelligence unavailable'],['missing','Asset not found']]){mode=m;await btc.click();await page.waitForFunction(t=>document.querySelector('.ai-content').textContent.includes(t),text);assert(await page.getByRole('button',{name:'Retry',exact:true}).isVisible());await x.click();}
  mode='populated';delay=700;await btc.click();assert.match(await modal.innerText(),/Loading asset intelligence/);await page.evaluate(()=>AssetIntelligence.open('ETH'));await page.waitForFunction(()=>document.querySelector('#ai-title').textContent==='ETH — Ethereum');await page.waitForSelector('#ai-events .ai-record');assert(!await modal.innerText().then(t=>t.includes('BTC')));delay=0;await x.click();
  // Native close events are queued: synchronous reopen must keep the new request and scroll lock.
  await btc.click();await page.evaluate(()=>{const d=document.querySelector('dialog');d.close();AssetIntelligence.open('ETH');});await page.waitForFunction(()=>document.querySelector('#ai-title').textContent==='ETH — Ethereum');await page.waitForSelector('#ai-events .ai-record');assert.equal(await page.evaluate(()=>document.body.style.overflow),'hidden');await x.click();assert.equal(await page.evaluate(()=>document.body.style.overflow),'');
  await page.locator('.header-asset button').first().click();await page.waitForFunction(()=>document.querySelector('#ai-title').textContent==='BTC — Bitcoin');await x.click();
  await page.evaluate(()=>refreshTradingUniverse());assert.equal(await page.locator('.universe-card').count(),10);assert.equal(await page.locator('#universe-assets').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),5);
  for(const folder of ['15minbot','1hrbot','4hrbot']){await page.goto(base+'/demo/'+folder+'/');await page.waitForSelector('.header-asset button');await page.locator('.header-asset button').first().click();await page.waitForFunction(()=>document.querySelector('#ai-title').textContent==='BTC — Bitcoin');for(const width of [320,375,768,1440]){await page.setViewportSize({width,height:700});assert.match(await page.locator('#ai-decision').innerText(),/SHADOW GO/);assert.match(await page.locator('#ai-sizing').innerText(),/SHADOW REDUCE/);assert.match(await page.locator('#ai-sizing').innerText(),/630 USDT/);assert.match(await page.locator('#ai-learning').innerText(),/learning-v1-baseline/);assert(await modal.evaluate(e=>e.scrollWidth<=e.clientWidth+1),'bot modal overflow '+folder+' '+width);}await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('dialog').open);
   await page.evaluate(()=>{const article=document.createElement('article');article.className='asset-path';article.dataset.pair='ETH/USDT:USDT';article.innerHTML='<h4>ETH/USDT</h4>';document.querySelector('main').append(article);});await page.locator('.asset-path button').last().click();await page.waitForFunction(()=>document.querySelector('#ai-title').textContent==='ETH — Ethereum');await page.getByRole('button',{name:'Close asset intelligence'}).click();
  }
  assert.deepEqual(errors,[]);console.log('PASS: Phase 6 sizing/USDT/notional/blocks/unavailable/expiry-timer/safe-text/all-bot-widths and Phase 5 shadow/current/no-go/blocked/stale/missing/future/safe-text/all-bot-widths and Phase 4 market/funding/OI/units/partial/stale/failure/unavailable/safe text and Phase 2 symbols/endpoints, independent timeframes, news/events, empty/partial/stale/404/503/loading, safe text, price freshness, X/Escape/backdrop, focus/scroll restoration, repeated opens, race cancellation, Top-10 refresh/5 columns, bot integration, 320/375/768/1440 layouts.');
 }finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1});
