const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const os = require('node:os');
(async () => {
 const browser = await chromium.launch({headless:true,channel:'msedge'});
 const page = await browser.newPage();
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 let staleStatus=false, failed=new Set(), staleMacro=false, staleMarket=false, nullMacro=false, statusCalls=0, strategy='Medium1hr';
 const symbols=['BTC','ETH','SOL','XRP','LINK','ONDO','AAVE','UNI','HYPE','INJ'];
 const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Australia/Brisbane'}).format(new Date());
 const stamp=()=>new Date().toISOString();
 await page.route('https://stream.radiorrr.com/**',r=>r.abort());
 await page.route('https://api.rrr.trading/**',r=>{
  const endpoint=new URL(r.request().url()).pathname;
  if(endpoint==='/status') statusCalls++;
  if(failed.has(endpoint)) return r.fulfill({status:503});
  let data;
  if(endpoint==='/score') data={ok:true,assets:symbols.slice(0,3).map(symbol=>({pair:symbol+'-USDT',trend_score:88,confidence:78}))};
  if(endpoint==='/api/market-summary') data={ok:true,currency:'USD',source:'kraken',updated_at:stamp(),markets:symbols.map((symbol,i)=>({symbol,price:[83675.57,2688.78,150,0.5234,10,1,200,5,40,8][i],change:i===1?-3.42:1,change_24h:i===1?-0.13:0.16,updated_at:staleMarket?new Date(Date.now()-180000).toISOString():stamp()}))};
  if(endpoint==='/api/reports/macro/today') data={report_type:'macro_base',timezone:'Australia/Brisbane',report_date:staleMacro?'2000-01-01':today(),generated_at:stamp(),macro_score:nullMacro?null:55,macro_regime:'Mixed'};
  if(endpoint==='/status') data={ok:true,generated_at:Date.now()/1000-(staleStatus?60:0),bot:{pairs:['BTC','ETH','SOL','XRP','LINK','ONDO','AAVE','UNI','HYPE','INJ'].map(a=>a+'/USDT:USDT'),mode:'PAPER',state:'RUNNING',strategy,exchange:'kraken',stake_currency:'USD',stake_amount:100,timeframe:'1h',max_open_trades:4,version:'test'},portfolio:{starting_balance:1000,profit_all_abs:20,profit_all_pct:2,open_positions:1,max_open_positions:4,winning_trades:2,losing_trades:1},open_trades:[{pair:'HYPE/USDT:USDT',direction:'SHORT',open_rate:80000,current_rate:81000,stake_amount:100,profit_abs:1,profit_pct:1,open_date:stamp()}],history:[{pair:'INJ/USDT:USDT',direction:'LONG',open_rate:2500,close_rate:2600,profit_abs:4,profit_pct:4,exit_reason:'roi',close_date:stamp()}]};
  return r.fulfill({json:data||{ok:true}});
 });
 await page.goto('http://localhost:8765/demo/');
 const settle=()=>page.waitForFunction(()=>document.querySelector('[data-asset=XRP] [data-field=price]')?.textContent==='$0.5234');
 await settle();
 assert.equal(await page.locator('#asset-analysis').evaluate(e=>e.open),false);
 assert(await page.locator('#asset-cards').isHidden());
 await page.locator('#assets-title').click();
 assert(await page.locator('#asset-cards').isVisible());
 assert.equal(await page.locator('#demo-macro-score').innerText(),'55 / 100');
 assert.equal(await page.locator('#demo-macro-regime').innerText(),'Mixed');
 assert.deepEqual(await page.locator('[data-asset]').evaluateAll(els=>els.map(e=>e.dataset.asset)),symbols);
 assert.equal(await page.locator('[data-asset=BTC] [data-field=trend]').innerText(),'88 / 100');
 assert.equal(await page.locator('[data-asset=XRP] [data-field=trend]').innerText(),'Awaiting analysis');
 assert.match(await page.locator('[data-asset=ETH] [data-field=daily-move]').innerText(),/−\$3.42 · −0.13%/);
 assert.match(await page.locator('.market-observed').first().innerText(),/Kraken · observed.*Brisbane/);
 assert.equal(await page.locator('#stateBadge').innerText(),'RUNNING');
 assert.match(await page.locator('#balance').innerText(),/1,000/);
 assert.equal(await page.locator('#winRate').innerText(),'66.7%');
 assert.equal(await page.locator('#openRows tr').count(),1);
 assert.equal(await page.locator('#historyRows tr').count(),1);
 assert.match(await page.locator('#openRows').innerText(),/HYPE\/USDT:USDT.*SHORT/s);
 assert.equal(await page.locator('#settings .setting').count(),6);
 assert.equal(await page.locator('#openPos').innerText(),'1 / 4');
 assert.equal(await page.locator('#settings .setting b').nth(4).innerText(),'4');
 assert.match(await page.locator('#pairUniverse').innerText(),/INJ\/USDT:USDT/);
 assert.equal(await page.locator('#settings .setting b').first().innerText(),'Medium 1hr');
 staleStatus=true; await page.evaluate(()=>load());
 assert.equal(await page.locator('#stateBadge').innerText(),'UNAVAILABLE');
 assert.equal(await page.locator('#pairUniverse').innerText(),'Trading universe unavailable');
 assert.equal(await page.locator('#openRows tr').count(),0);
 staleStatus=false; strategy='Medium 1hr'; await page.evaluate(()=>load());
 assert.match(await page.locator('#pairUniverse').innerText(),/INJ\/USDT:USDT/);
 assert.equal(await page.locator('#settings .setting b').first().innerText(),'Medium 1hr');
 assert.equal(await page.locator('#settings .setting b').nth(2).innerText(),'1h');
 const positions=await page.locator('.top,.demo-macro,.grid,#settings,#openRows,#historyRows,.demo-assets').evaluateAll(els=>els.map(e=>e.getBoundingClientRect().top));
 assert(positions.every((v,i)=>i===0||v>positions[i-1]));
 assert(await page.evaluate(()=>document.querySelector('#asset-analysis').getBoundingClientRect().top>document.querySelector('#historyRows').getBoundingClientRect().bottom));
 for(const width of [320,768,1024,1440]) {
  await page.setViewportSize({width,height:1000});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Demo overflow '+width);
  const cols=await page.locator('#asset-cards').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length);
  assert.equal(cols,width<=600?1:width<=1100?2:4);
  await page.screenshot({path:path.join(os.tmpdir(),`rrr-demo-${width}.png`),fullPage:true});
  const tradesTop=await page.locator('#openRows').evaluate(e=>e.getBoundingClientRect().top+scrollY);
  await page.locator('#assets-title').focus();
  await page.keyboard.press('Enter');
  assert(await page.locator('#asset-cards').isHidden());
  assert.equal(await page.locator('#openRows').evaluate(e=>e.getBoundingClientRect().top+scrollY),tradesTop,'Collapsing analysis must not move trades');
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Collapsed demo overflow '+width);
  await page.screenshot({path:path.join(os.tmpdir(),`rrr-demo-collapsed-${width}.png`),fullPage:true});
  await page.keyboard.press('Space');
  assert(await page.locator('#asset-cards').isVisible());
 }
 // Refresh only the new analysis polls; the existing status loop is unchanged.
 const refresh=async()=>{await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await page.waitForTimeout(300);};
 staleMacro=true; await refresh();
 assert.equal(await page.locator('#demo-macro-score').innerText(),'N/A');
 assert.match(await page.locator('#demo-macro-regime').innerText(),/Stale/);
 staleMacro=false; nullMacro=true; await refresh();
 assert.equal(await page.locator('#demo-macro-score').innerText(),'N/A');
 assert.equal(await page.locator('#demo-macro-regime').innerText(),'Awaiting macro data');
 nullMacro=false; staleMarket=true; await refresh();
 assert.equal(await page.locator('[data-asset=BTC] [data-field=price]').innerText(),'Unavailable');
 assert.match(await page.locator('.market-observed').first().innerText(),/Stale/);
 assert.equal(await page.locator('[data-asset=BTC] [data-field=trend]').innerText(),'88 / 100');
 staleMarket=false; failed.add('/score'); await refresh(); await settle();
 assert.equal(await page.locator('[data-asset=BTC] [data-field=trend]').innerText(),'Awaiting analysis');
 assert.equal(await page.locator('#stateBadge').innerText(),'RUNNING');
 failed=new Set(['/score','/api/market-summary','/api/reports/macro/today','/status']);
 await refresh(); await page.evaluate(()=>load());
 assert.equal(await page.locator('[data-asset]').count(),10);
 assert.equal(await page.locator('#demo-macro-score').innerText(),'N/A');
 assert.equal(await page.locator('#stateBadge').innerText(),'UNAVAILABLE');
 assert.equal(await page.locator('#openRows tr').count(),0);
 assert.equal(await page.locator('#historyRows tr').count(),0);
 failed.clear(); await refresh(); await page.evaluate(()=>load()); await settle();
 assert.equal(await page.locator('#stateBadge').innerText(),'RUNNING');
 await page.evaluate(()=>{const a=document.querySelector('audio');let paused=true;Object.defineProperty(a,'paused',{get:()=>paused});a.play=async()=>{paused=false;a.dispatchEvent(new Event('playing'));};a.pause=()=>{paused=true;a.dispatchEvent(new Event('pause'));};});
 await page.locator('#radio-toggle').click(); assert.equal(await page.locator('#radio-toggle').getAttribute('aria-pressed'),'true');
 await page.locator('#radio-toggle').click(); assert.equal(await page.locator('#radio-toggle').getAttribute('aria-pressed'),'false');
 const initial=statusCalls; await page.waitForTimeout(15500); assert(statusCalls>initial,'15-second status refresh');
 await page.locator('#navigation [data-page=home]').click();
 assert.equal(new URL(page.url()).pathname,'/');
 assert.equal(await page.locator('#asset-analysis,#asset-cards,[data-asset]').count(),0);
 assert.deepEqual(errors,[]);
 await browser.close();
 console.log('PASS: asset analysis below trades/history and collapsed by default, mouse/keyboard toggle, expanded/collapsed responsive layouts, XRP exchange fields, saved macro, failures/stale states/recovery, account/open/history, radio/navigation, 15-second status refresh and no JS errors.');
})().catch(e=>{console.error(e);process.exitCode=1;});
