const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const os = require('node:os');
(async () => {
 const browser = await chromium.launch({headless:true,channel:"msedge"});
 const page = await browser.newPage(); const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 let failure=false, partial=false, empty=false;
 const asset={pair:'BTC-USDT',direction:'LONG',trade_allowed:true,confidence:78,leverage:1.5,technical_score:82,trend_score:88,sentiment_score:50,risk_score:76,risk_gate:'normal',sentiment_source:'placeholder'};
 await page.route('https://api.rrr.trading/**', route=>{
  const path=new URL(route.request().url()).pathname;
  if(failure || partial && path==='/score') return route.fulfill({status:503,body:'Unavailable'});
  const data=path==='/score'?{ok:true,assets:[asset,{...asset,pair:'SOL-USDT',trade_allowed:false,risk_gate:'blocked',leverage:0}]}:path==='/market-regime'?{ok:true,market_regime:'neutral',average_confidence:67}:{ok:true,bot:{mode:'PAPER',state:'RUNNING',strategy:'Test strategy',exchange:'Test exchange',timeframe:'4h',stake_currency:'USDT'},portfolio:{starting_balance:empty?null:1000,profit_all_abs:0,open_positions:0,max_open_positions:3,winning_trades:0,losing_trades:0}};
  return route.fulfill({json:data});
 });
 await page.goto('http://localhost:8765'); await page.waitForFunction(()=>document.querySelector('#assessment-regime')?.textContent === 'NEUTRAL');
 assert.equal(await page.locator('[data-report]').count(),7);
 assert.equal(await page.locator('[data-asset], #asset-analysis, #asset-cards').count(),0);
 assert.equal(await page.locator('#assessment-regime').innerText(),'NEUTRAL');
 assert.equal(await page.locator('#assessment-trend').innerText(),'Awaiting analysis');
 assert.equal(await page.locator('#snapshot, #sentiment-cards, #scoring-title, #about, #leverage-title').count(),0);
 assert.deepEqual(await page.locator('main > section').evaluateAll(els=>els.map(e=>e.id)),['','macro-base','market-inputs','daily-assessment','demo-summary','today','reports']);
 await page.locator('#navigation [data-page=today]').click();
 assert.equal(new URL(page.url()).hash,'#today');
 await page.waitForFunction(()=>document.querySelector('#report-captured').textContent.includes('Template'));
 assert.equal(await page.locator('#report-status').innerText(),'');
 assert.equal(await page.locator('#report-archive a').count(),3);
 assert.equal(await page.locator('#demo-summary .primary').getAttribute('href'),'/demo');
 assert.equal(await page.locator('audio').evaluate(a=>a.autoplay),false);
 assert.equal(await page.locator('audio').getAttribute('src'),'https://stream.radiorrr.com/radio.mp3');
 await page.evaluate(()=>{
  const audio=document.querySelector('audio');
  let paused=true;
  Object.defineProperty(audio,'paused',{get:()=>paused});
  audio.play=async()=>{paused=false;audio.dispatchEvent(new Event('playing'));};
  audio.pause=()=>{paused=true;audio.dispatchEvent(new Event('pause'));};
 });
 await page.locator('#radio-toggle').click();
 assert.equal(await page.locator('#radio-toggle').getAttribute('aria-pressed'),'true');
 await page.locator('#radio-toggle').click();
 assert.equal(await page.locator('#radio-toggle').getAttribute('aria-pressed'),'false');
 const demos=await page.locator('a').evaluateAll(els=>els.filter(e=>/demo/i.test(e.textContent)).map(e=>e.getAttribute('href'))); assert(demos.every(h=>h==='/demo'));
 for(const width of [1920,1440,1024,768,390,320]) {await page.setViewportSize({width,height:900}); assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow at ${width}`);}
 await page.screenshot({path:path.join(os.tmpdir(),'rrr-homepage-mobile-check.png'),fullPage:true});
 await page.setViewportSize({width:1440,height:1000}); await page.screenshot({path:path.join(os.tmpdir(),'rrr-homepage-desktop-check.png'),fullPage:true});
 empty=true; await page.evaluate(()=>refreshStatus()); assert.match(await page.locator('#bot-metrics').innerText(),/Starting balance\n—/);
 partial=true; await page.evaluate(()=>refreshStatus()); assert.match(await page.locator('#bot-metrics').innerText(),/RUNNING/);
 failure=true; await page.evaluate(()=>Promise.all([refreshStatus(),refreshRegime()])); assert.equal(await page.locator('#assessment-regime').innerText(),'Awaiting analysis'); assert.doesNotMatch(await page.locator('#bot-metrics').innerText(),/RUNNING/);
 await page.locator('#report-archive a').first().click();
 assert.match(page.url(),/reports\/2026-09-29.html$/);
 await page.goto('http://localhost:8765');
 await page.locator('#demo-summary .primary').click(); await page.waitForFunction(()=>document.querySelector('#stateBadge').textContent==='UNAVAILABLE');
 assert.equal(errors.length,0,errors.join('\n'));
 console.log('PASS: desktop/mobile 1920/1440/1024/768/390/320; API fixtures, missing values, partial/full failures, report loading, archive, navigation and demo CTA, radio controls with mocked playback, demo path.');
 await browser.close();
})().catch(e=>{console.error(e);process.exitCode=1});
