const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const os = require('node:os');
(async () => {
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage(); const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 let failure=false, stale=false, reportFailure=false;
 const expectedDay=()=>{const now=new Date();const hour=Number(new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Brisbane',hour:'2-digit',hourCycle:'h23'}).format(now));return new Intl.DateTimeFormat('en-CA',{timeZone:'Australia/Brisbane'}).format(hour<7?new Date(now.getTime()-86400000):now);};
 const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Australia/Brisbane'}).format(new Date());
 await page.route('https://stream.radiorrr.com/**',r=>r.abort());
 await page.route('**/data/daily-crypto-report.html',r=>reportFailure?r.fulfill({status:503}):r.continue());
 await page.route('https://api.rrr.trading/**',r=>{
  if(failure) return r.fulfill({status:503});
  const endpoint=new URL(r.request().url()).pathname;
  const data=endpoint==='/market-regime'?{market_regime:'neutral',average_confidence:64.1}:endpoint.startsWith('/api/reports/macro/')?{report_type:'macro_base',timezone:'Australia/Brisbane',report_date:stale?'2000-01-01':expectedDay(),generated_at:expectedDay()+'T07:00:00+10:00',macro_score:55,macro_regime:'Mixed',confidence:80,scoring:{coverage:0.8},components:Object.fromEntries(['rates','usd','equities','liquidity','volatility','macro_events'].map(k=>[k,{score:k==='macro_events'?null:55,status:'Mixed',summary:'Unavailable',provenance:{observations:k==='rates'?[{series_id:'DGS10',value:4.1,observation_date:today(),fresh:false}]:[]}}]))}:{};
  return r.fulfill({json:data});
 });
 await page.goto('http://localhost:8765');
 await page.waitForFunction(()=>document.querySelector('#macro-score').textContent==='55');
 assert.deepEqual(await page.locator('main > section').evaluateAll(es=>es.map(e=>e.id)),['','top-opportunities','intelligence-inputs','traderouter-intelligence','current-universe','trading-bots']);
 assert.equal(await page.locator('#market-inputs,[data-report]').count(),0);
 assert.equal(await page.locator('#today,#reports,#daily-report,#bot-metrics').count(),0);
 assert.equal(await page.locator('#navigation [data-page=today]').count(),0);
 assert.equal(await page.locator('#homepage-bots .paper-card').count(),3);
 assert.equal(await page.locator('#intelligence-regime').innerText(),'Unavailable');
 assert.equal(await page.locator('#macro-score').innerText(),'55');
 assert.match(await page.locator('#macro-components').textContent(),/stale, excluded/);
 assert.doesNotMatch(await page.locator('main .eyebrow').allTextContents().then(es=>es.join(' ')), /\d\d \//);
 assert.doesNotMatch(await page.locator('main').innerText(),/Awaiting analysis|Trading weight|Not configured/);
 assert.equal(await page.locator('#demo-summary,[data-paper]').count(),0);
 assert.equal(await page.locator('.input-card').count(),0);
 assert.deepEqual(await page.locator('#homepage-bots a').evaluateAll(es=>es.map(e=>e.getAttribute('href'))),['/demo/15minbot/','/demo/1hrbot/','/demo/4hrbot/']);
 for(const width of [320,375,768,1024,1440,1920]) {
  await page.setViewportSize({width,height:900});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Home overflow '+width);
 }
 await page.screenshot({path:path.join(os.tmpdir(),'rrr-homepage-desktop-check.png'),fullPage:true});
 await page.setViewportSize({width:375,height:900});
 await page.screenshot({path:path.join(os.tmpdir(),'rrr-homepage-mobile-check.png'),fullPage:true});
 stale=true; await page.evaluate(()=>refreshMacro());
 assert.equal(await page.locator('#macro-score').innerText(),'—');
 assert.match(await page.locator('#macro-summary').innerText(),/current 7 am Brisbane reporting cycle/);
 failure=true; await page.evaluate(()=>Promise.all([refreshHomepageIntelligence(),refreshMacro()]));
 assert.equal(await page.locator('#intelligence-regime').innerText(),'Unavailable');
 assert.match(await page.locator('#intelligence-status').innerText(),/unavailable/);
 assert.match(await page.locator('#macro-summary').innerText(),/unavailable/);
 await page.evaluate(()=>{const a=document.querySelector('audio');let paused=true;Object.defineProperty(a,'paused',{get:()=>paused});a.play=async()=>{paused=false;a.dispatchEvent(new Event('playing'));};a.pause=()=>{paused=true;a.dispatchEvent(new Event('pause'));};});
 assert.equal(await page.locator('audio').getAttribute('src'),'https://stream.radiorrr.com/radio.mp3');
 assert.equal(await page.locator('audio').evaluate(a=>a.autoplay),false);
 await page.locator('#radio-toggle').click(); assert.equal(await page.locator('#radio-toggle').getAttribute('aria-pressed'),'true');
 await page.locator('#radio-toggle').click(); assert.equal(await page.locator('#radio-toggle').getAttribute('aria-pressed'),'false');
 const reportPage=await page.request.get('http://localhost:8765/reports.html');
 assert.equal(reportPage.status(),404);
 assert.equal(await page.locator('#navigation a').evaluateAll(links=>links.some(link=>/reports/i.test(link.textContent)||/reports\.html/i.test(link.getAttribute('href')||''))),false);
 assert.deepEqual(errors,[]);
 await browser.close(); console.log('PASS: homepage hierarchy, macro/intelligence fixtures, unavailable/stale states, removed Reports page, radio controls, no console errors; Home at 320/375/768/1024/1440/1920.');
})().catch(e=>{console.error(e);process.exitCode=1});
