const {chromium}=require('playwright'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
(async()=>{
 const server=http.createServer((req,res)=>{let file=path.join(__dirname,new URL(req.url,'http://local').pathname);if(file.endsWith(path.sep))file+='index.html';fs.readFile(file,(e,b)=>{if(e)return res.writeHead(404).end();res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(b);});});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});
 try{
 const page=await browser.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));
 const base=process.env.RRR_SCHEDULE_BASE_URL||`http://127.0.0.1:${server.address().port}`;
 let scenario='healthy',release,held;
 const iso=offset=>new Date(Date.now()+offset*1000).toISOString();
 function fixture(){const generated=iso(scenario==='stale'?-90000:scenario==='future'?3600:-10),at=iso(86400);
  const previous={series_id:'UNRATE',label:'Unemployment rate',value:0,units:'Percent',frequency:'Monthly, seasonally adjusted',observation_period:'2026-08-01',status:'available',vintage:'Latest revised observation; not original pre-release information',retrieved_at:generated,source_url:'https://fred.stlouisfed.org/series/UNRATE'};
  const events=[{id:'cpi',country:'US',title:'Consumer Price Index <img src=x onerror="window.injected=1">',source:'FRED',release_date:at.slice(0,10),release_timezone:'America/New_York',scheduled_at:at,time_status:'VERIFIED',time_source:'https://www.bls.gov/schedule/news_release/bls.ics',source_url:'https://fred.stlouisfed.org/release?rid=10',previous:[previous],forecast:99},
   {id:'employment',country:'US',title:'Employment Situation',source:'FRED',release_date:at.slice(0,10),release_timezone:'America/New_York',scheduled_at:null,time_status:'DATE CONFIRMED, TIME UNAVAILABLE',source_url:'https://fred.stlouisfed.org/release?rid=50',previous:[{...previous,value:null,status:'unavailable'}]},
   {id:'rba',country:'AU',title:'RBA Monetary Policy Board meeting concludes',source:'RBA',release_date:at.slice(0,10),release_timezone:'Australia/Sydney',scheduled_at:null,time_status:'DATE CONFIRMED, TIME UNAVAILABLE',source_url:'https://www.rba.gov.au/schedules-events/board-meeting-schedules.html',previous:[]}];
  if(scenario==='partial')events[0].stale=true;
  if(scenario==='safe-links'){events[0].source_url='javascript:window.injected=1';events[0].time_source='https://evil.example/?x';events[0].previous[0].source_url='https://fred.stlouisfed.org@evil.example/';}
  if(scenario==='invalid-time')events[0].scheduled_at='2026-10-15T08:30:00';
  if(scenario==='previous-stale')events[0].previous[0].status='stale';
  return {schema_version:1,status:scenario==='partial'?'partial':'ok',generated_at:generated,expires_at:iso(scenario==='stale'?-10:86300),stale:false,events:scenario==='empty'?[]:events,
   health:{fred_status:scenario==='partial'?'partial':'ok',stale:false,last_successful_fred_refresh:generated,upcoming_releases:3,verified_timestamps:1,last_successful_international_refresh:generated,international_status:'partial',errors:scenario==='partial'?[{release_id:10,error:'FRED release schedule unavailable'}]:[],official_sources:{BLS:{status:'ok',last_success:generated},RBA:{status:'unavailable',error:'Official RBA calendar unavailable'}}},coverage_gaps:['Consensus forecasts unavailable.','ECB/BoE/BoJ coverage unavailable.']};}
 await page.route('https://stream.radiorrr.com/**',r=>r.abort());
 await page.route('https://api.rrr.trading/**',async r=>{const url=new URL(r.request().url());requests.push({path:url.pathname,method:r.request().method()});if(url.pathname.startsWith('/api/schedule/')){if(scenario==='loading')await held;if(scenario==='outage')return r.fulfill({status:503,json:{}});if(scenario==='404')return r.fulfill({status:404,json:{}});if(scenario==='malformed')return r.fulfill({json:{schema_version:1,status:'ok',events:'wrong'}});if(scenario==='timeout')return;return r.fulfill({json:fixture()});}return r.fulfill({status:503,json:{}});});
 const load=async()=>{await page.goto(base+'/schedule/');await page.waitForFunction(()=>document.getElementById('schedule-refresh').disabled===false);};
 await load();assert.equal(await page.locator('.schedule-event').count(),3);assert.equal(await page.locator('.event-countdown').count(),1);assert.match(await page.locator('.schedule-event').first().innerText(),/AEST/);assert.match(await page.locator('.schedule-event').first().innerText(),/0 · Percent/);assert.match(await page.locator('.schedule-event').first().innerText(),/Reporting period: 2026-08-01/);assert.match(await page.locator('.schedule-event').first().innerText(),/Forecast unavailable/);assert(!await page.locator('#schedule-events img').count());assert(!await page.evaluate(()=>window.injected));
 await page.locator('#schedule-region').selectOption('AU');assert.equal(await page.locator('.schedule-event').count(),1);assert.match(await page.locator('.schedule-event').innerText(),/TIME UNAVAILABLE/);await page.locator('#schedule-region').selectOption('all');
 for(const width of [320,375,768,1440]){await page.setViewportSize({width,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+width);assert(await page.locator('.schedule-event').evaluateAll(rows=>rows.every(e=>e.scrollWidth<=e.clientWidth+1)));if(width===1440)assert.equal(await page.locator('#schedule-events').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),2);fs.mkdirSync(path.join(__dirname,'.runtime/schedule'),{recursive:true});await page.screenshot({path:path.join(__dirname,`.runtime/schedule/calendar-${width}.png`),fullPage:true});}
 // Failure retains dated evidence but suspends every current numeric/time claim.
 scenario='outage';await page.locator('#schedule-refresh').click();await page.waitForFunction(()=>!document.getElementById('schedule-refresh').disabled);assert.equal(await page.locator('.event-countdown').count(),0);assert.match(await page.locator('#schedule-status').innerText(),/unavailable/);assert(!/0 · Percent/.test(await page.locator('#schedule-events').innerText()));
 for(scenario of ['stale','future','partial','previous-stale','invalid-time','empty','safe-links','404','malformed']){await load();const body=await page.locator('main').innerText();if(['stale','future','partial','invalid-time','404','malformed'].includes(scenario))assert.equal(await page.locator('.event-countdown').count(),0,scenario);if(scenario==='partial')assert.match(body,/Partial calendar coverage/);if(scenario==='previous-stale')assert.match(body,/Stale historical observation/);if(scenario==='empty')assert.match(body,/No upcoming announcements/);if(scenario==='safe-links')assert.equal(await page.locator('#schedule-events a').evaluateAll(links=>links.filter(a=>!['fred.stlouisfed.org','www.bls.gov','www.bea.gov','www.rba.gov.au'].includes(new URL(a.href).hostname)).length),0);}
 scenario='loading';held=new Promise(r=>release=r);await page.goto(base+'/schedule/');assert.match(await page.locator('#schedule-status').innerText(),/Loading/);scenario='healthy';release();await page.waitForSelector('.schedule-event');
 scenario='timeout';await page.locator('#schedule-refresh').click();await page.waitForFunction(()=>!document.getElementById('schedule-refresh').disabled,{},{timeout:16000});assert.match(await page.locator('#schedule-status').innerText(),/unavailable/);
 scenario='healthy';await page.goto(base+'/tools/');await page.waitForFunction(()=>document.getElementById('calendar-monitoring-status').textContent.includes('FRED calendar'));await page.locator('#calendar-monitoring summary').click();assert.match(await page.locator('#calendar-monitoring-evidence').innerText(),/Verified timestamps: 1/);assert.match(await page.locator('#calendar-monitoring-gaps').innerText(),/RBA: official calendar unavailable/);
 for(const width of [320,375,768,1440]){await page.setViewportSize({width,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 scenario='outage';await page.locator('#refresh').click();await page.waitForFunction(()=>document.getElementById('calendar-monitoring-status').textContent.includes('unavailable or stale'));assert(await page.locator('#calendar-monitoring').evaluate(e=>e.open));
 assert(requests.every(r=>r.method==='GET'));assert.equal(errors.length,0,errors.join('\n'));console.log('PASS schedule FRED calendar: sources/units/revisions/times/unknown/stale/partial/failures/safe text/GET-only/Tools/320/375/768/1440');
 }finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exit(1);});
