const {chromium}=require('playwright'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
(async()=>{
const server=http.createServer((req,res)=>{let file=path.join(__dirname,new URL(req.url,'http://local').pathname);if(file.endsWith(path.sep))file+='index.html';fs.readFile(file,(e,b)=>{if(e)return res.writeHead(404).end();res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(b);});});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});
try{
const page=await browser.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));let scenario='healthy',calls=0;
const card=(id,status='healthy')=>({id,name:id+' <script>unsafe</script>',status,reason:'Real fixture evidence',rows:Array.from({length:6},(_,i)=>({label:'Metric '+i,value:i})),observed_at:new Date().toISOString()});
const snapshot=()=>({schema_version:1,timestamp:new Date().toISOString(),valid_until:new Date(Date.now()+75000).toISOString(),overall_status:scenario==='blocked'?'execution_blocked':'operational',explanation:'Execution verified in deterministic fixture only',services:[card('API'),card('Tunnel','unknown')],intelligence:[card('News',scenario==='stale'?'stale':'healthy')],bots:[card('15 MIN','waiting'),card('1 HR','blocked'),card('4 HR','unknown')],execution:[card('Admission')],api_health:[{id:'api',name:'API',endpoint:'/safe',status:'healthy',http_code:200,response_ms:4}],recent_activity:[{id:'1',at:new Date().toISOString(),category:'bots',message:'Actual fixture timestamp',status:'healthy'},{id:'2',at:new Date().toISOString(),category:'errors',message:'Failure <img src=x onerror=alert(1)>',status:'failed'}],monitoring_gaps:['Docker metrics unavailable']});
await page.route('https://api.rrr.trading/**',async r=>{requests.push(r.request().method());if(!r.request().url().endsWith('/api/v2/system/health'))return r.fulfill({status:503,json:{}});calls++;if(scenario==='outage')return r.fulfill({status:503,json:{}});if(scenario==='timeout')return;return r.fulfill({json:snapshot()});});
await page.goto(`http://127.0.0.1:${server.address().port}/tools/`);await page.waitForFunction(()=>document.querySelector('#overall-title').textContent==='OPERATIONAL');
assert.equal(await page.locator('.operating-modes .mode-button').count(),4);assert.equal(await page.locator('[data-page="tools"][aria-current="page"]').count(),1);
assert.equal(await page.locator('#services script').count(),0);assert((await page.locator('#services h3').first().innerText()).includes('<script>'));
await page.locator('#services details').first().evaluate(e=>e.open=true);await page.getByRole('button',{name:'BOTS',exact:true}).click();
await page.evaluate(()=>SystemHealth.refresh());await page.waitForFunction(()=>!document.querySelector('#refresh').hasAttribute('aria-busy'));assert(await page.locator('#services details').first().evaluate(e=>e.open));assert.equal(await page.locator('#activity li').count(),1);
scenario='blocked';await page.evaluate(()=>SystemHealth.refresh());await page.waitForFunction(()=>document.querySelector('#overall-title').textContent==='EXECUTION BLOCKED');
scenario='outage';await page.evaluate(()=>SystemHealth.refresh());await page.waitForFunction(()=>document.querySelector('#overall-title').textContent.includes('STALE'));assert.equal(await page.locator('#services .healthy').count(),0);assert(await page.locator('#services details').first().evaluate(e=>e.open));
scenario='healthy';await page.evaluate(()=>SystemHealth.refresh());await page.waitForFunction(()=>document.querySelector('#overall-title').textContent==='OPERATIONAL');
for(const width of [320,375,768,1440]){await page.setViewportSize({width,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));if([375,1440].includes(width))await page.screenshot({path:`.runtime/tools-${width}.png`,fullPage:true});}
// Expiry even when no request completes; all previous green is removed.
await page.evaluate(()=>{const now=Date.now;Date.now=()=>now()+76000;});await page.waitForFunction(()=>document.querySelector('#overall-title').textContent.includes('STALE'));assert.equal(await page.locator('.tools-dashboard .healthy').count(),0);
// Poll cadence and timeout are verified using the browser clock.
scenario='timeout';await page.clock.install();await page.reload();await page.clock.fastForward(13000);await page.waitForFunction(()=>document.querySelector('#overall-title').textContent==='UNKNOWN');const prior=calls;scenario='healthy';await page.clock.fastForward(18000);await page.waitForFunction(()=>document.querySelector('#overall-title').textContent==='OPERATIONAL');assert(calls>prior);
for(const route of ['/','/demo/15minbot/','/demo/1hrbot/','/demo/4hrbot/']){await page.goto(`http://127.0.0.1:${server.address().port}${route}`);assert.equal(await page.locator('.operating-modes .mode-button').count(),4);assert.equal(await page.getByRole('link',{name:'TOOLS',exact:true}).getAttribute('href'),'/tools/');}
assert.deepEqual(errors,[]);assert(requests.every(x=>x==='GET'));console.log('PASS tools: safe text, states, failed refresh/expiry, retained panels/filter, 30s polling/12s timeout, four widths, four primary navigation buttons/all bots, GET-only');
}finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1});
