const {chromium}=require('playwright'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
(async()=>{
const server=http.createServer((req,res)=>{let file=path.join(__dirname,new URL(req.url,'http://local').pathname);if(file.endsWith(path.sep))file+='index.html';fs.readFile(file,(e,b)=>{if(e)return res.writeHead(404).end();res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(b);});});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});
try{
const page=await browser.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));let scenario='healthy',calls=0,calendarScenario='phase2';
const card=(id,status='healthy')=>({id,name:id+' <script>unsafe</script>',status,reason:'Real fixture evidence',rows:Array.from({length:6},(_,i)=>({label:'Metric '+i,value:i})),observed_at:new Date().toISOString()});
const snapshot=()=>({schema_version:1,monitoring_version:'health-evidence-v2',timestamp:new Date().toISOString(),valid_until:new Date(Date.now()+75000).toISOString(),overall_status:scenario==='blocked'?'execution_blocked':'operational',core_platform_status:'operational',execution_readiness:'not_verified',monitoring_coverage:'partial',explanation:'Execution verified in deterministic fixture only',services:[card('public'),card('tunnel','unknown'),card('gate','unknown'),card('admin','unknown'),card('short_service'),card('medium_service'),card('long_service')],intelligence:['scanner','universe','market','technical','news','macro','events','scoring','sync'].map(id=>card(id,id==='news'&&scenario==='stale'?'stale':'healthy')),bots:[card('short','waiting'),card('medium','blocked'),card('long','not_verified')],execution:['discovery','signals','validation','risk','execution','orders','positions','short_exits','medium_exits','long_exits'].map(id=>card(id,id==='orders'?'not_verified':'healthy')),api_health:[{id:'api',name:'API',endpoint:'/safe',status:'healthy',http_code:200,response_ms:4,checked_at:new Date().toISOString(),last_success_at:new Date().toISOString()}],issues:[{id:'news',component:'Asset news',problem:'Current source failure <img src=x onerror=alert(1)>',severity:'warning',impact:'Reduced coverage',first_detected_at:new Date().toISOString(),last_observed_at:new Date().toISOString(),target:'news'},{id:'orders',component:'Order connectivity',problem:'Not independently observed',severity:'monitoring_gap',impact:'Verification incomplete',target:'orders'}],recent_activity:[{id:'1',at:new Date().toISOString(),category:'bots',message:'Actual fixture transition',status:'healthy'},{id:'1',at:new Date().toISOString(),category:'bots',message:'Duplicate fixture transition',status:'healthy'},{id:'routine',at:new Date().toISOString(),category:'system',message:'Intelligence monitoring check healthy',status:'healthy'},{id:'2',at:new Date().toISOString(),category:'errors',message:'Failure <img src=x onerror=alert(1)>',status:'failed'}],monitoring_gaps:['Docker metrics unavailable']});
await page.route('https://api.rrr.trading/**',async r=>{requests.push(r.request().method());if(r.request().url().endsWith('/api/schedule/health')){if(calendarScenario==='outage')return r.fulfill({status:503,json:{}});const h={fred_status:'ok',international_status:'partial',stale:calendarScenario==='stale',upcoming_releases:30,verified_timestamps:14,official_sources:{BLS:{status:'unavailable'}}};if(calendarScenario==='phase2')Object.assign(h,{calendar_status:'PARTIAL COVERAGE',classification_version:'rrr-economic-impact-v1',high_impact_events:30,date_only_events:16,unclassified_events:6});return r.fulfill({json:{schema_version:1,status:calendarScenario==='stale'?'stale':'partial',generated_at:new Date().toISOString(),health:h,coverage_gaps:['Official coverage <script>unsafe</script>']}});}if(!r.request().url().endsWith('/api/v2/system/health'))return r.fulfill({status:503,json:{}});calls++;if(scenario==='outage')return r.fulfill({status:503,json:{}});if(scenario==='timeout')return;const value=snapshot();if(scenario==='legacy')for(const field of ['core_platform_status','execution_readiness','monitoring_coverage','issues','monitoring_version'])delete value[field];if(scenario==='missing-timestamp')delete value.timestamp;if(scenario==='backend-stale')value.stale=true;if(scenario==='gap-only')value.issues=value.issues.filter(i=>i.severity==='monitoring_gap');return r.fulfill({json:value});});
await page.goto(`http://127.0.0.1:${server.address().port}/tools/`);await page.waitForFunction(()=>document.querySelector('#overall-title').textContent==='OPERATIONAL');
await page.locator('#calendar-monitoring summary').click();await page.waitForFunction(()=>document.querySelector('#calendar-monitoring-evidence').textContent.includes('HIGH impact: 30'));assert.match(await page.locator('#calendar-monitoring-status').innerText(),/PARTIAL COVERAGE/);assert.match(await page.locator('#calendar-monitoring-evidence').innerText(),/Date-only: 16.*Unclassified: 6/);assert.equal(await page.locator('#calendar-monitoring script').count(),0);assert.equal(await page.locator('#overall-title').innerText(),'OPERATIONAL');
for(calendarScenario of ['legacy','stale','outage','phase2']){await page.locator('#refresh').click();await page.waitForFunction(()=>!document.getElementById('refresh').hasAttribute('aria-busy'));await page.waitForTimeout(50);assert(await page.locator('#calendar-monitoring').evaluate(e=>e.open));if(['stale','outage'].includes(calendarScenario)){assert.match(await page.locator('#calendar-monitoring-status').innerText(),/unavailable or stale/);assert(!/HIGH impact: 30/.test(await page.locator('#calendar-monitoring-evidence').innerText()));}if(calendarScenario==='legacy')assert(!/Classification:/.test(await page.locator('#calendar-monitoring-evidence').innerText()));assert.equal(await page.locator('#overall-title').innerText(),'OPERATIONAL');}
assert.equal(await page.locator('.operating-modes .mode-button').count(),4);assert.equal(await page.locator('[data-page="tools"][aria-current="page"]').count(),1);
assert.equal(await page.locator('#services script').count(),0);assert((await page.locator('#services h3').first().innerText()).includes('<script>'));
assert.equal(await page.locator('#services article').count(),4);assert.equal(await page.locator('#intelligence article').count(),8);assert.equal(await page.locator('#execution article').count(),6);
assert.equal(await page.locator('#core-status').innerText(),'OPERATIONAL');assert.equal(await page.locator('#readiness-status').innerText(),'NOT VERIFIED');assert.equal(await page.locator('#coverage-status').innerText(),'PARTIAL');
assert.equal(await page.locator('#api-details').evaluate(e=>e.open),false);assert((await page.locator('#api-summary').innerText()).includes('Slowest handler: 4 ms'));
await page.locator('#api-details > summary').click();assert.equal(await page.locator('#api-details').evaluate(e=>e.open),true);assert((await page.locator('#api_health').innerText()).includes('Handler execution duration'));
assert.equal(await page.locator('#issues img').count(),0);assert((await page.locator('#issues').innerText()).includes('MONITORING GAP'));
await page.locator('#issues button').first().click();assert(await page.locator('#intelligence [data-key="news"] details').evaluate(e=>e.open));
assert.equal(await page.locator('#activity li').count(),2);
await page.locator('#services details').first().evaluate(e=>e.open=true);await page.getByRole('button',{name:'BOTS',exact:true}).click();
await page.evaluate(()=>SystemHealth.refresh());await page.waitForFunction(()=>!document.querySelector('#refresh').hasAttribute('aria-busy'));assert(await page.locator('#services details').first().evaluate(e=>e.open));assert.equal(await page.locator('#activity li').count(),1);
scenario='blocked';await page.evaluate(()=>SystemHealth.refresh());await page.waitForFunction(()=>document.querySelector('#overall-title').textContent==='EXECUTION BLOCKED');
scenario='outage';await page.evaluate(()=>SystemHealth.refresh());await page.waitForFunction(()=>document.querySelector('#overall-title').textContent.includes('STALE'));assert.equal(await page.locator('#services .healthy').count(),0);assert(await page.locator('#services details').first().evaluate(e=>e.open));
scenario='healthy';await page.evaluate(()=>SystemHealth.refresh());await page.waitForFunction(()=>document.querySelector('#overall-title').textContent==='OPERATIONAL');
scenario='legacy';await page.evaluate(()=>SystemHealth.refresh());await page.waitForFunction(()=>!document.querySelector('#refresh').hasAttribute('aria-busy'));assert.equal(await page.locator('#core-status').innerText(),'NOT VERIFIED');assert((await page.locator('#issues').innerText()).includes('awaits the monitoring backend'));
for(const value of ['missing-timestamp','backend-stale']){scenario=value;await page.evaluate(()=>SystemHealth.refresh());await page.waitForFunction(()=>document.querySelector('#overall-title').textContent.includes('STALE'));assert.equal(await page.locator('.tools-dashboard .healthy').count(),0);}
scenario='gap-only';await page.evaluate(()=>SystemHealth.refresh());await page.waitForFunction(()=>document.querySelector('#overall-title').textContent==='OPERATIONAL');assert((await page.locator('#issues').innerText()).includes('NO ACTIVE OPERATIONAL ISSUES DETECTED'));assert((await page.locator('#issues').innerText()).includes('Monitoring coverage is partial'));
scenario='healthy';await page.evaluate(()=>SystemHealth.refresh());await page.waitForFunction(()=>!document.querySelector('#refresh').hasAttribute('aria-busy'));
for(const width of [320,375,768,1440]){await page.setViewportSize({width,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));if([375,1440].includes(width))await page.screenshot({path:`.runtime/tools-${width}.png`,fullPage:true});}
// Expiry even when no request completes; all previous green is removed.
await page.evaluate(()=>{const now=Date.now;Date.now=()=>now()+76000;});await page.waitForFunction(()=>document.querySelector('#overall-title').textContent.includes('STALE'));assert.equal(await page.locator('.tools-dashboard .healthy').count(),0);
// Poll cadence and timeout are verified using the browser clock.
scenario='timeout';await page.clock.install();await page.reload();await page.clock.fastForward(13000);await page.waitForFunction(()=>document.querySelector('#overall-title').textContent==='NOT VERIFIED');const prior=calls;scenario='healthy';await page.clock.fastForward(18000);await page.waitForFunction(()=>document.querySelector('#overall-title').textContent==='OPERATIONAL');assert(calls>prior);
for(const route of ['/','/demo/15minbot/','/demo/1hrbot/','/demo/4hrbot/']){await page.goto(`http://127.0.0.1:${server.address().port}${route}`);assert.equal(await page.locator('.operating-modes .mode-button').count(),4);assert.equal(await page.getByRole('link',{name:'TOOLS',exact:true}).getAttribute('href'),'/tools/');}
assert.deepEqual(errors,[]);assert(requests.every(x=>x==='GET'));console.log('PASS tools: safe text, states, failed refresh/expiry, retained panels/filter, 30s polling/12s timeout, four widths, four primary navigation buttons/all bots, GET-only');
}finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1});
