const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
(async()=>{
 const server=http.createServer((req,res)=>{const file=path.join(__dirname,new URL(req.url,'http://localhost').pathname.replace(/\/$/,'/index.html'));fs.readFile(file,(err,data)=>{if(err)return res.writeHead(404).end();res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(data);});});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 try{
  const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  let failure=false,stale=false,expired=false,malformed=false,missingCounts=false;
  const assets='BTC ETH SOL XRP LINK ONDO AAVE UNI HYPE INJ'.split(' ').map((symbol,i)=>({rank:i+1,symbol,pair:symbol+'/USDT:USDT',opportunity_score:87-i,reason:'Fixture momentum evidence. Missing directional research.',trend:'positive',macro_fit_score:60,theme_score:65,research_score:null,catalyst_score:null,data_coverage:.7,data_confidence:.8,themes:['defi'],approved_for_new_entries:true}));
  const payload=()=>({schema_version:1,status:stale?'stale':'ok',reason:stale?'Retaining last-known-good selection':null,generated_at:new Date(Date.now()-3600000).toISOString(),valid_until:new Date(Date.now()+(expired?-1800000:86400000)).toISOString(),universe_version:'fixture-v1',researched_market_count:missingCounts?undefined:100,scoring_eligible_count:missingCounts?undefined:87,entry_eligible:!expired,macro_regime:'neutral',assets:malformed?assets.slice(0,9):assets,changes:{added:['LINK'],removed:['DOGE']},bot_sync:Object.fromEntries(['short','medium','long'].map(b=>[b,{status:b==='long'?'stale':'current',loaded:10,expected:10,universe_version:b==='long'?'old':'fixture-v1',checked_at:new Date().toISOString(),legacy_open_positions:b==='long'?[{pair:'DOGE/USDT:USDT'}]:[]}]))});
  await page.route('https://stream.radiorrr.com/**',r=>r.abort());
  await page.route('https://api.rrr.trading/**',r=>new URL(r.request().url()).pathname==='/api/trading-universe'?(failure?r.fulfill({status:503}):r.fulfill({json:payload()})):r.fulfill({status:503}));
  await page.goto('http://127.0.0.1:'+server.address().port);
  await page.waitForFunction(()=>document.querySelectorAll('.universe-card').length===10);
  assert.match(await page.locator('#universe-summary').innerText(),/10 selected from 100 researched Bybit perpetual markets · 87 currently eligible/);
  assert.match(await page.locator('#universe-status').innerText(),/Continuously researched/);
  assert.equal(await page.locator('.universe-card').count(),10);
  assert.equal(await page.locator('.universe-analysis-reason').count(),10);
  await page.locator('.universe-bubble').first().click();
  await page.waitForSelector('#asset-intelligence-dialog[open]');
  assert.match(await page.locator('#ai-title').innerText(),/BTC/);assert.match(await page.locator('.ai-selection').innerText(),/Fixture momentum evidence/);
  await page.getByRole('button',{name:'Close asset intelligence'}).click();
  const first = page.locator('.universe-bubble').first();
  await first.focus(); await first.press('Enter');
  assert(await page.locator('#asset-intelligence-dialog').evaluate(e=>e.open));
  await page.keyboard.press('Escape');
  await page.waitForFunction(()=>!document.querySelector('#asset-intelligence-dialog').open);
  assert(await first.evaluate(e=>e===document.activeElement));
  await page.locator('#how-it-works>.dashboard-details>summary').click();
  assert.match(await page.locator('#universe-sync').innerText(),/CURRENT · 10\/10 assets loaded/);
  assert.match(await page.locator('#universe-sync').innerText(),/STALE/);
  assert.match(await page.locator('#universe-sync').innerText(),/DOGE\/USDT:USDT/);
  for(const width of [320,375,768,1024,1280,1440,1920]){
   await page.setViewportSize({width,height:900});
   assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow '+width);
   const layout = await page.locator('#universe-assets').evaluate(e=>({rows:new Set([...e.children].map(c=>Math.round(c.getBoundingClientRect().top))).size,visible:e.clientWidth/e.firstElementChild.getBoundingClientRect().width,overflow:e.scrollWidth>e.clientWidth}));
   assert.equal(layout.rows,1);
   assert(layout.overflow);
   const expected = width >= 1200 ? 7 : width >= 900 ? 4 : width >= 700 ? 3.5 : 1.75;
   assert(Math.abs(layout.visible-expected)<.7,JSON.stringify(layout));
   if([375,1440].includes(width))await page.screenshot({path:'.runtime/universe-'+width+'.png',fullPage:true});
  }
  await page.setViewportSize({width:1440,height:900});
  await page.emulateMedia({reducedMotion:'reduce'});
  const track=page.locator('#universe-assets');
  const shell=page.locator('.asset-carousel').first();
  await track.scrollIntoViewIfNeeded();
  await track.evaluate(e=>e.scrollLeft=0);
  const box=await track.boundingBox();
  await page.mouse.move(box.x+250,box.y+80);await page.mouse.down();
  await page.mouse.move(box.x+150,box.y+80,{steps:5});
  assert.equal(await track.evaluate(e=>getComputedStyle(e).scrollSnapType),'none');
  assert.equal(await track.evaluate(e=>getComputedStyle(e).cursor),'grabbing');
  assert(Math.abs(await track.evaluate(e=>e.scrollLeft)-100)<2);
  await page.mouse.up();
  assert(!(await page.locator('#asset-intelligence-dialog').evaluate(e=>e.open)));
  assert.match(await track.evaluate(e=>getComputedStyle(e).scrollSnapType),/^x( proximity)?$/);
  await page.mouse.move(box.x+150,box.y+80);await page.mouse.down();
  await page.mouse.move(box.x+250,box.y+80,{steps:5});await page.mouse.up();
  await page.waitForFunction(()=>document.querySelector('#universe-assets').scrollLeft<2);
  await page.locator('#universe-assets .universe-bubble').first().click();
  assert(await page.locator('#asset-intelligence-dialog').evaluate(e=>e.open));
  await page.keyboard.press('Escape');
  await track.dispatchEvent('pointerdown',{pointerType:'touch',pointerId:90,button:0,clientX:200});
  assert(!(await track.evaluate(e=>e.classList.contains('is-dragging'))));
  assert.equal(await track.evaluate(e=>getComputedStyle(e).touchAction),'auto');
  await page.mouse.move(box.x+200,box.y+80);await page.mouse.down();
  await page.mouse.move(box.x+190,box.y+80);await page.evaluate(()=>dispatchEvent(new Event('blur')));await page.mouse.up();
  assert(!(await track.evaluate(e=>e.classList.contains('is-dragging'))));
  await track.evaluate(e=>e.scrollLeft=0);
  await page.waitForFunction(()=>document.querySelector('.asset-carousel-arrow').disabled);
  await shell.getByRole('button',{name:'Next assets'}).click();
  await page.waitForFunction(()=>document.querySelector('#universe-assets').scrollLeft>0);
  const step=await track.evaluate(e=>e.firstElementChild.getBoundingClientRect().width+parseFloat(getComputedStyle(e).gap));
  assert(Math.abs(await track.evaluate(e=>e.scrollLeft)-3*step)<3);
  await page.waitForFunction(()=>document.querySelector('.asset-carousel').dataset.after==='false');
  assert(await shell.getByRole('button',{name:'Next assets',includeHidden:true}).isDisabled());
  await shell.getByRole('button',{name:'Previous assets'}).click();
  await page.waitForFunction(()=>document.querySelector('#universe-assets').scrollLeft<2);
  await track.hover();await page.mouse.wheel(0,100);
  await page.waitForFunction(()=>document.querySelector('#universe-assets').scrollLeft>0);
  assert.equal(await page.evaluate(()=>scrollX),0);
  await page.setViewportSize({width:375,height:900});
  await track.scrollIntoViewIfNeeded();await track.evaluate(e=>e.scrollLeft=0);
  const touchBox=await track.boundingBox(),cdp=await page.context().newCDPSession(page);
  await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true});
  async function swipe(x,y,dx,dy){
   await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});
   for(let i=1;i<=8;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+dx*i/8,y:y+dy*i/8}]});
   await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  }
  await swipe(touchBox.x+250,touchBox.y+100,-170,0);
  await page.waitForFunction(()=>document.querySelector('#universe-assets').scrollLeft>20);
  assert(!(await track.evaluate(e=>e.classList.contains('is-dragging'))));
  const beforeY=await page.evaluate(()=>scrollY);
  await swipe(touchBox.x+150,touchBox.y+150,0,-100);
  await page.waitForFunction(y=>scrollY>y+20,beforeY);
  await cdp.detach();
  missingCounts=true;await page.evaluate(()=>refreshTradingUniverse());assert.match(await page.locator('#universe-summary').innerText(),/coverage unavailable/);missingCounts=false;
  stale=true;await page.evaluate(()=>refreshTradingUniverse());assert.match(await page.locator('#universe-status').innerText(),/Stale/);assert.equal(await page.locator('.universe-card').count(),10);
  expired=true;await page.evaluate(()=>refreshTradingUniverse());assert.equal(await page.locator('.universe-entry-state').allTextContents().then(es=>es.filter(e=>e==='New entries blocked').length),10);
  assert.doesNotMatch(await page.locator('#universe-sync').innerText(),/CURRENT/);
  malformed=true;await page.evaluate(()=>refreshTradingUniverse());assert.equal(await page.locator('.universe-card').count(),0);
  malformed=false;failure=true;await page.evaluate(()=>refreshTradingUniverse());assert.equal(await page.locator('.universe-card').count(),0);assert.match(await page.locator('#universe-status').innerText(),/unavailable/);
  assert.deepEqual(errors,[]);
  console.log('PASS: 10 real-contract cards, missing inputs, version-aware bot sync, legacy positions, expiry, malformed/unavailable states, desktop/mobile layouts; no page errors.');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
