(() => {
'use strict';
const status=document.getElementById('calendar-monitoring-status'),evidence=document.getElementById('calendar-monitoring-evidence'),gaps=document.getElementById('calendar-monitoring-gaps');
let snapshot=null,busy=false,failed=false,controller;
const at=v=>typeof v==='string'&&/(Z|[+-]\d{2}:\d{2})$/.test(v)&&Number.isFinite(Date.parse(v))?new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Brisbane',dateStyle:'medium',timeStyle:'short'}).format(new Date(v))+' AEST':'Unavailable';
function render(){const stamp=Date.parse(snapshot?.generated_at),h=snapshot?.health||{},fresh=!failed&&Number.isFinite(stamp)&&stamp<=Date.now()+30000&&Date.now()-stamp<=86400000&&h.stale===false;
status.textContent=!fresh?'Economic calendar unavailable or stale; Schedule coverage cannot be verified.':`FRED calendar ${['ok','partial','unavailable'].includes(h.fred_status)?h.fred_status:'unavailable'} · International coverage ${h.international_status==='partial'?'partial':'unavailable'}`;
evidence.textContent=`Last successful FRED refresh: ${at(h.last_successful_fred_refresh)} · Upcoming releases: ${fresh&&Number.isInteger(h.upcoming_releases)?h.upcoming_releases:'Unavailable'} · Verified timestamps: ${fresh&&Number.isInteger(h.verified_timestamps)?h.verified_timestamps:'Unavailable'} · Last international refresh: ${at(h.last_successful_international_refresh)}`;
gaps.replaceChildren();for(const item of snapshot?.coverage_gaps||['Saved calendar backend connection unavailable.','Consensus forecasts unavailable.']){const li=document.createElement('li');li.textContent=typeof item==='string'?item:'Coverage unverified';gaps.append(li);}for(const item of Array.isArray(h.errors)?h.errors:[]){const li=document.createElement('li');li.textContent=`FRED release ${Number.isInteger(item.release_id)?item.release_id:'unknown'}: unavailable`;gaps.append(li);}for(const item of Array.isArray(h.observation_errors)?h.observation_errors:[]){const li=document.createElement('li');li.textContent=`FRED historical series ${typeof item.series_id==='string'?item.series_id:'unknown'}: unavailable or stale`;gaps.append(li);}
for(const [name,value] of Object.entries(h.official_sources||{})){if(value?.status==='ok')continue;const li=document.createElement('li');li.textContent=`${name}: official calendar unavailable`;gaps.append(li);}}
async function refresh(){if(busy)return;busy=true;controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),12000);try{const r=await fetch('https://api.rrr.trading/api/schedule/health',{method:'GET',cache:'no-store',signal:controller.signal});if(!r.ok)throw Error();const data=await r.json();if(data?.schema_version!==1||!data.health||!Array.isArray(data.coverage_gaps))throw Error();snapshot=data;failed=false;}catch{failed=true;}finally{clearTimeout(timeout);busy=false;render();}}
refresh();document.getElementById('refresh').addEventListener('click',refresh);const poll=setInterval(()=>{if(!document.hidden)refresh();},60000),age=setInterval(()=>{if(snapshot&&Date.now()-Date.parse(snapshot.generated_at)>86400000)render();},1000);window.addEventListener('pagehide',()=>{clearInterval(poll);clearInterval(age);controller?.abort();});
})();
