'use strict';
(() => {
const endpoint='https://api.rrr.trading/api/v2/system/health';
const groups=['services','intelligence','bots','execution','api_health'];
const statuses=new Set(['healthy','operational','ready','waiting','blocked','execution_blocked','degraded','offline','failed','unknown','not_verified','partial','complete','unavailable','stale','timeout']);
const inventory={services:['Public Trading API','Cloudflare Tunnel','15 MIN BOT','1 HR BOT','4 HR BOT','Legacy gate service','Administration service'],intelligence:['Market scanner','Trading universe','Market data','Technical analysis','Asset news','Macro intelligence','Event intelligence','Candidate scoring','Universe synchronisation'],bots:['15 MIN BOT','1 HR BOT','4 HR BOT'],execution:['Candidate discovery','Technical signal evaluation','Intelligence validation','Risk assessment','Execution admission','Order submission connectivity','Open position monitoring','15 MIN BOT exits','1 HR BOT exits','4 HR BOT exits'],api_health:['Consolidated monitoring API']};
const clock=new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Brisbane',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false});
let snapshot=null,received=0,failed=false,busy=false,filter='all',timer;
const text=v=>v===null||v===undefined||v===''?'Unavailable':typeof v==='boolean'?v?'Yes':'No':String(v);
const at=v=>Number.isFinite(Date.parse(v))?clock.format(new Date(v))+' Brisbane':'Unavailable';
const relative=v=>{const t=typeof v==='string'?Date.parse(v):NaN;if(!Number.isFinite(t)||t>Date.now()+30000)return 'NOT VERIFIED';const s=Math.max(0,Math.floor((Date.now()-t)/1000));return s<60?`${s} seconds ago`:s<3600?`${Math.floor(s/60)} minutes ago`:`${Math.floor(s/3600)} hours ago`;};
const display=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(v)&&Number.isFinite(Date.parse(v))?relative(v):text(v);
const node=(tag,content,cls)=>{const n=document.createElement(tag);if(content!==undefined)n.textContent=text(content);if(cls)n.className=cls;return n;};
const stale=()=>failed||!snapshot||snapshot.stale===true||!Number.isFinite(Date.parse(snapshot.timestamp))||!Number.isFinite(Date.parse(snapshot.valid_until))||Date.now()>Date.parse(snapshot.valid_until)||Date.now()-Date.parse(snapshot.timestamp)>75000||Date.parse(snapshot.timestamp)>Date.now()+30000;
function state(value){return statuses.has(value)?value:'unknown';}
function paintStatus(n,status,label){status=state(status);if(status==='unknown')status='not_verified';n.className='health-status '+status;n.textContent=label||status.replaceAll('_',' ').toUpperCase();}
function renderGroup(key,provided){
 const host=document.getElementById(key);let items=provided||(Array.isArray(snapshot?.[key])?snapshot[key].slice(0,30):inventory[key].map((name,i)=>({id:key+i,name,status:'not_verified',reason:failed?'Monitoring evidence unavailable.':'Awaiting consolidated backend evidence.',rows:[]})));
 if(key==='services')items=items.filter(c=>!['tunnel','gate','admin'].includes(c.id)&&!['Cloudflare Tunnel','Legacy gate service','Administration service'].includes(c.name));
 if(key==='intelligence')items=items.filter(c=>c.id!=='events'&&c.name!=='Event intelligence');
 if(!items.length){host.replaceChildren(node('p','Monitoring evidence unavailable.','data-note'));return;}
 const present=new Set();
 for(const item of items){if(!item||typeof item.id!=='string')continue;present.add(item.id);
  let card=[...host.children].find(c=>c.dataset.key===item.id);
  if(!card){card=node('article',undefined,'health-card');card.dataset.key=item.id;card.append(node('h3'),node('div',undefined,'health-status'),node('p'),node('dl'),node('details'));card.lastChild.append(node('summary','View observation details'),node('dl'));host.append(card);}
  card.children[0].textContent=text(item.name);
  const status=snapshot&&stale()?'stale':state(item.status);paintStatus(card.children[1],status);
  card.children[2].textContent=text(item.reason||item.basis);
  const rows=key==='api_health'?[{label:'GET endpoint',value:item.endpoint},{label:'Handler response code',value:item.http_code},{label:'Handler execution duration (ms)',value:item.response_ms},{label:'Last successful check',value:item.last_success_at},{label:'Last checked',value:item.checked_at}]:Array.isArray(item.rows)?item.rows.slice(0,25):[];
  const appendRows=(target,list,precise=false)=>{target.replaceChildren();for(const r of list){const pair=node('div');pair.append(node('dt',r.label),node('dd',precise?text(r.value):display(r.value)));target.append(pair);}};
  const visible=rows.filter(r=>!['Container state','Uptime / CPU / memory / restarts'].includes(r.label)&&!/(saved total|insufficient evidence|Missing decision evidence)/i.test(r.label)).slice(0,key==='bots'?9:key==='execution'?1:3);
  appendRows(card.children[3],visible);appendRows(card.lastChild.lastChild,rows.concat([{label:'Precise observation time',value:item.observed_at}] ),true);
  for(const d of item.diagnostics||[]){const section=node('div',undefined,'diagnostic-observation');section.dataset.observation=d.id;section.append(node('strong',d.name),node('p',`${text(d.status).replaceAll('_',' ').toUpperCase()} · ${text(d.reason)}`));const dl=node('dl');appendRows(dl,d.rows||[],true);section.append(dl);card.lastChild.lastChild.append(section);}
 }
 for(const c of [...host.children])if(!present.has(c.dataset.key))c.remove();
}
function activity(){const list=document.getElementById('activity');list.replaceChildren();const seen=new Set();const events=(Array.isArray(snapshot?.recent_activity)?snapshot.recent_activity:[]).filter(e=>{if(!e||seen.has(e.id)||/monitoring check|saved activity evidence/.test(e.message))return false;seen.add(e.id);return true;}).filter(e=>filter==='all'||e.category===filter||filter==='errors'&&['failed','degraded','offline','blocked','timeout'].includes(e.status)).slice(0,20);for(const e of events){const li=node('li');li.append(node('time',at(e.at)),node('span',e.message));list.append(li);}if(!events.length)list.append(node('li',snapshot?'No supported significant events for this filter.':'Event evidence unavailable.'));}
function pipeline(){const source=snapshot?.execution||[];const stages=[['discovery','DISCOVERY',['discovery']],['signals','SIGNALS',['signals']],['validation','INTELLIGENCE',['validation']],['risk','RISK',['risk']],['execution','EXECUTION',['execution','orders']],['monitoring','MONITORING',['positions','short_exits','medium_exits','long_exits']]];
 const priority=['offline','failed','blocked','degraded','stale','timeout','not_verified','unknown','unavailable','waiting','healthy'];
 renderGroup('execution',stages.map(([id,name,ids])=>{const evidence=source.filter(c=>ids.includes(c.id));const observed=priority.find(s=>evidence.some(c=>c.status===s))||'not_verified';const status=evidence.length<ids.length&&['healthy','waiting'].includes(observed)?'not_verified':observed;const reason=evidence.find(c=>c.status===status)?.reason||'Stage observation is incomplete';const activity=evidence.map(c=>c.observed_at).filter(v=>Number.isFinite(Date.parse(v))).sort((a,b)=>Date.parse(b)-Date.parse(a))[0];return {id,name,status,reason,rows:[{label:'Last observed activity',value:activity}],diagnostics:evidence};}));
}
function apiSummary(){const probes=snapshot?.api_health||[],healthy=probes.filter(p=>p.status==='healthy').length;const ms=probes.map(p=>p.response_ms).filter(Number.isFinite);const checked=probes.map(p=>p.checked_at).filter(v=>Number.isFinite(Date.parse(v))).sort((a,b)=>Date.parse(b)-Date.parse(a))[0];document.getElementById('api-summary').textContent=stale()?'API checks NOT VERIFIED · current snapshot unavailable':`${healthy} / ${probes.length} HEALTHY · Failed or incomplete checks: ${probes.length-healthy} · Slowest handler: ${ms.length?Math.max(...ms)+' ms':'NOT VERIFIED'} · Last checked: ${relative(checked)}`;}
function issues(){const host=document.getElementById('issues');host.replaceChildren();if(stale()){host.append(node('p','Current issues cannot be verified; snapshot unavailable or expired.','data-note'));return;}
 if(!Array.isArray(snapshot.issues)){host.append(node('p','Detailed issue classification awaits the monitoring backend refinement. Existing component statuses remain visible.','data-note'));return;}
 const findings=snapshot.issues.slice(0,16);if(!findings.some(i=>i.severity!=='monitoring_gap'))host.append(node('p','NO ACTIVE OPERATIONAL ISSUES DETECTED','data-note'));
 if(snapshot.monitoring_coverage==='partial')host.append(node('p','Monitoring coverage is partial.','data-note'));
 for(const severity of ['critical','warning','monitoring_gap']){const group=findings.filter(i=>i.severity===severity);if(!group.length)continue;host.append(node('h3',severity.replaceAll('_',' ').toUpperCase(),severity));for(const issue of group){const button=node('button',undefined,'issue '+severity);button.type='button';button.append(node('strong',issue.component),node('span',issue.problem),node('small',`${text(issue.impact)} · First detected ${relative(issue.first_detected_at)} · Last observed ${relative(issue.last_observed_at)}`));button.addEventListener('click',()=>{let target=[...document.querySelectorAll('[data-key],[data-observation]')].find(n=>n.dataset.key===issue.target||n.dataset.observation===issue.target);if(issue.target==='api_health')target=document.getElementById('api-details');if(target){for(let p=target;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;const details=target.querySelector('details');if(details)details.open=true;target.scrollIntoView({block:'center',behavior:'auto'});const focus=target.querySelector('summary')||target;focus.tabIndex=0;focus.focus({preventScroll:true});}});host.append(button);}}
}
function render(){
 const expired=stale(),n=document.getElementById('overall-title');
 document.body.dataset.snapshotExpired=String(expired);
 paintStatus(n,expired?'not_verified':snapshot.overall_status,expired?(snapshot?'NOT VERIFIED · STALE SNAPSHOT':'NOT VERIFIED') : undefined);
 document.getElementById('overall-reason').textContent=expired?(snapshot?'The last successful snapshot is retained. Current system readiness cannot be verified.':'Consolidated monitoring is unavailable. Backend deployment or connectivity must be verified; API reachability alone does not establish trading readiness.'):text(snapshot.explanation);
 const age=received?Math.max(0,Math.floor((Date.now()-received)/1000)):null;
 document.getElementById('updated').textContent=received?`Last successful response ${age}s ago · backend snapshot ${at(snapshot.timestamp)}${expired?' · STALE':''}`:'No successful monitoring update · automatic retry every 30 seconds';
 for(const [id,field] of [['core-status','core_platform_status'],['readiness-status','execution_readiness'],['coverage-status','monitoring_coverage']])paintStatus(document.getElementById(id),expired?'not_verified':snapshot?.[field]||'not_verified');
 groups.filter(k=>k!=='execution').forEach(k=>renderGroup(k));pipeline();apiSummary();activity();issues();const gaps=document.getElementById('gaps');gaps.replaceChildren();for(const gap of (snapshot?.monitoring_gaps||['Consolidated endpoint not yet available','Container and trading readiness cannot be inferred from a responding API']))gaps.append(node('li',gap));
}
async function refresh(){if(busy)return;busy=true;const button=document.getElementById('refresh');button.setAttribute('aria-busy','true');button.textContent='Checking…';const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),12000);try{const response=await fetch(endpoint,{method:'GET',cache:'no-store',signal:controller.signal});if(!response.ok)throw Error('Check unavailable');const value=await response.json();if(value?.schema_version!==1||!groups.every(k=>Array.isArray(value[k]))||!statuses.has(value.overall_status))throw Error('Invalid snapshot');snapshot=value;received=Date.now();failed=false;}catch{failed=true;}finally{clearTimeout(timeout);busy=false;button.removeAttribute('aria-busy');button.textContent='↻ Refresh';render();}}
for(const name of ['all','system','intelligence','bots','execution','errors']){const button=node('button',name.toUpperCase());button.type='button';button.setAttribute('aria-pressed',String(name===filter));button.addEventListener('click',()=>{filter=name;for(const b of button.parentElement.children)b.setAttribute('aria-pressed',String(b===button));activity();});document.getElementById('activity-filters').append(button);}
document.getElementById('refresh').addEventListener('click',refresh);
groups.filter(k=>k!=='execution').forEach(k=>renderGroup(k));pipeline();refresh();timer=setInterval(refresh,30000);const ageTimer=setInterval(()=>{if(snapshot&&stale()&&document.body.dataset.snapshotExpired!=='true')render();else if(received)document.getElementById('updated').textContent=`Last successful response ${Math.max(0,Math.floor((Date.now()-received)/1000))}s ago · backend snapshot ${at(snapshot.timestamp)}${stale()?' · STALE':''}`;},1000);
window.SystemHealth=Object.freeze({refresh});window.addEventListener('pagehide',()=>{clearInterval(timer);clearInterval(ageTimer);});
})();
